### PR TITLE
Fix conflicting type arguments error

### PR DESCRIPTION
**Pull request by nfekete**

### CODE REVIEW

**Comment by lalmeras** [comment]
Thanks for the new PR. I try to review and merge this fix this week.

**Comment by lalmeras** [comment]
I just refactor a big project to use a recent version of bindgen, so that I can proof-test this fix on a real use-case. Work in progress...

**Comment by lalmeras** [comment]
Validated in my big project. Tests are OK. I merge this PR.

**Comment by nfekete** [comment]
Awesome, thanks!

**Pull request merged**
