### PR TITLE
Fix conflicting type arguments error

### PR DESCRIPTION
**Pull request by nfekete**
This patch fixes the conflicting type arguments error when generating
bindings for generic types that use R or P as type arguments, described
at: https://github.com/igloo-project/bindgen/issues/3

The changed behavior will look through a list of preferred type argument
names for both the root and path type arguments, and will pick the first
available one. In case the preferred list of type argument names is
exhausted, it will generate one with the first preferred type argument
name, combined with a number, so that the newly generated name is not
conflicting with any of the type argument names that are already used by
the type for which the binding is generated. The preferred name for the
bindings are:

 - R, ROOT, ROOT_TYPE, or the first available from R_1, R_2, etc.
 - P, PATH, PATH_TYPE, or the first available from P_1, P_2, etc.

### CODE REVIEW

**Comment by nfekete** [comment]
Hello guys! Can you check on this PR? Also, #8 should probably be reopened since #9 was incomplete, but I can only submit a PR for the complete fix if this PR is merged, as it's based on top of it.

**Comment by lalmeras** [comment]
Sorry, I wrongly assumed the PR was still not complete.

I reopen #8 so that we can work on the complete fix.

For this PR, I just generate bindings on one of our project to compare newly generated sources with the old ones.

I see no issue, except this (just a formatting difference, with extraneous space chars in generics declaration):

``` diff
diff -Nru basic-application-core/apt-bindgen-old/org/iglooproject/jpa/business/generic/model/GenericEntityReferenceBindingPath.java basic-application-core/target/generated-sources/apt/org/iglooproject/jpa/business/generic/model/GenericEntityReferenceBindingPath.java
--- basic-application-core/apt-bindgen-old/org/iglooproject/jpa/business/generic/model/GenericEntityReferenceBindingPath.java   2019-02-05 19:53:47.720847591 +0100
+++ basic-application-core/target/generated-sources/apt/org/iglooproject/jpa/business/generic/model/GenericEntityReferenceBindingPath.java      2019-02-05 19:57:15.826415777 +0100
@@ -12,8 +12,8 @@
 import org.iglooproject.commons.util.binding.AbstractCoreBinding;
 
 @SuppressWarnings("all")
-@Generated(value = "org.bindgen.processor.Processor", date = "05 févr. 2019 07:53")
-public class GenericEntityReferenceBindingPath<R, P, K extends java.lang.Object&java.lang.Comparable<K>&java.io.Serializable, E extends org.iglooproject.jpa.business.generic.model.GenericEntity<K,?>> extends AbstractCoreBinding<R, P, GenericEntityReference<K,E>> {
+@Generated(value = "org.bindgen.processor.Processor", date = "05 févr. 2019 07:57")
+public class GenericEntityReferenceBindingPath<R, P, K extends java.lang.Object&java.lang.Comparable<K>&java.io.Serializable, E extends org.iglooproject.jpa.business.generic.model.GenericEntity<K,?>> extends AbstractCoreBinding< R,   P, GenericEntityReference<K,E>> {
 
     private IntegerBindingPath<R, GenericEntityReference<K,E>> hashCodeBinding;
     private StringBindingPath<R, GenericEntityReference<K,E>> toStringBinding;
```

If it doesn't involve heavy or difficult rewrites, I'd like to keep correctly formatted generated sources. I'll try to see if it can be fixed.

**Comment by nfekete** [comment]
@lalmeras I've found  the reason for the whitespace differences. I tried to refer to the positional parameters of `String.format` but instead I was specifying the minimal string with of them, so they where padded to the specified length from the left with spaces. This typo didn't create a semantic bug only because the strings were referred to in the actual positional order anyway.

Thanks for the good catch!

**Comment by nfekete** [comment]
I don't really know what happened, but github closed this PR for me and I can't seem to be able to reopen it. I will open a new one.

**Comment by nfekete** [comment]
What might have changed is that github no longer sees igloo-project/bindgen as a fork so our repositories are considered unrelated. This means that I can't even open a new pull request from my current fork. I'll try to create a new fork based on your repository and see whether it solves the problem.

**Comment by florianlacreuse** [comment]
@nfekete I confirm that our repository `igloo-project/bindgen` is a standalone repository and not a fork anymore since the last 2 months. We asked GitHub team to detach the fork.

**Comment by lalmeras** [comment]
Nice you fix this little issue about source formatting. As stated by @florianlacreuse, we ask to github to detach our repository from the original project (as it is no longer maintained, and forked project lacks some feature, as search tools). I think this project status change that invalidates your PR.

I cannot reopen it on my side. Can you open a new PR ?

Thanks

**Comment by nfekete** [comment]
I resubmitted the PR with the above mentioned fix as #14.

**Pull request closed without merging**
